annotations:
  artifacthub.io/images: |
    - name: ghcr.io/renovatebot/renovate:37.269.2
      image: ghcr.io/renovatebot/renovate:37.269.2
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/license: AGPL-3.0-only
  artifacthub.io/links: |
    - name: docs
      url: https://docs.renovatebot.com
apiVersion: v2
appVersion: 37.269.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.19.4
description: Universal dependency update tool that fits into your workflows.
home: https://github.com/renovatebot/renovate
icon: https://docs.renovatebot.com/assets/images/logo.png
keywords:
- automated
- dependencies
- dependency
- management
- update
maintainers:
- email: jamie.magee@gmail.com
  name: JamieMagee
- email: michael.kriese@visualon.de
  name: viceice
- email: rhys@arkins.net
  name: rarkins
name: renovate
sources:
- https://github.com/renovatebot/renovate
- https://github.com/renovatebot/helm-charts
version: 37.269.2
